// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUL-Ig0L1GCwTyY5TRCU0pZqfI1FqHyFI',
    appId: '1:539403801786:web:9968559ebc5c64b0ff1e83',
    messagingSenderId: '539403801786',
    projectId: 'air-guard-fyp',
    authDomain: 'air-guard-fyp.firebaseapp.com',
    databaseURL:
        'https://air-guard-fyp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'air-guard-fyp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABIawS80KdQUYp614qhbkdAnOtvw4oBuA',
    appId: '1:539403801786:android:c9b61671a71618cdff1e83',
    messagingSenderId: '539403801786',
    projectId: 'air-guard-fyp',
    databaseURL:
        'https://air-guard-fyp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'air-guard-fyp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCnnh1v8Lxjz6PRd4Gj5XQiuIExKaiin4',
    appId: '1:539403801786:ios:cd98c528ead7aef4ff1e83',
    messagingSenderId: '539403801786',
    projectId: 'air-guard-fyp',
    databaseURL:
        'https://air-guard-fyp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'air-guard-fyp.firebasestorage.app',
    iosBundleId: 'com.example.airGuard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCnnh1v8Lxjz6PRd4Gj5XQiuIExKaiin4',
    appId: '1:539403801786:ios:cd98c528ead7aef4ff1e83',
    messagingSenderId: '539403801786',
    projectId: 'air-guard-fyp',
    databaseURL:
        'https://air-guard-fyp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'air-guard-fyp.firebasestorage.app',
    iosBundleId: 'com.example.airGuard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUL-Ig0L1GCwTyY5TRCU0pZqfI1FqHyFI',
    appId: '1:539403801786:web:d2bec9ae5cff4a2cff1e83',
    messagingSenderId: '539403801786',
    projectId: 'air-guard-fyp',
    authDomain: 'air-guard-fyp.firebaseapp.com',
    databaseURL:
        'https://air-guard-fyp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'air-guard-fyp.firebasestorage.app',
  );
}
